import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import slideOne from "../assets/Images/ppt22.webp";
import slideTwo from "../assets/Images/ppt23.webp";
import slideThree from "../assets/Images/pptsix.webp";
import slideFour from "../assets/Images/ppt25.webp";
import slideFive from "../assets/Images/ppt26.webp";
import slideSix from "../assets/Images/ppt27.webp";
import { FaRocket, FaChevronLeft, FaChevronRight } from 'react-icons/fa';

const Projects = ({setIsUser}) => {
    const slides = [slideOne, slideTwo, slideThree, slideFour, slideFive, slideSix];
    const [currentIndex, setCurrentIndex] = useState(0);

    const handlePrev = () => {
        setCurrentIndex((prev) => (prev === 0 ? slides.length - 1 : prev - 1));
    };

    const handleNext = () => {
        setCurrentIndex((prev) => (prev === slides.length - 1 ? 0 : prev + 1));
    };

    // Calculate position for each slide in the carousel
    const getSlideStyle = (index) => {
        const diff = index - currentIndex;
        const normalizedDiff = diff > slides.length / 2 ? diff - slides.length : diff < -slides.length / 2 ? diff + slides.length : diff;
        
        // Position calculations for curved effect
        const angle = normalizedDiff * 30; // Angle spread
        const translateX = normalizedDiff * 350; // Horizontal spacing
        const translateZ = Math.abs(normalizedDiff) * -400; // Depth (negative = further back)
        const rotateY = -normalizedDiff * 35; // Rotation for 3D effect
        const scale = 1 - Math.abs(normalizedDiff) * 0.2; // Scale based on position
        const opacity = Math.abs(normalizedDiff) > 2 ? 0 : 1 - Math.abs(normalizedDiff) * 0.3;
        
        return {
            transform: `translateX(${translateX}px) translateZ(${translateZ}px) rotateY(${rotateY}deg) scale(${scale})`,
            opacity: opacity,
            zIndex: 10 - Math.abs(normalizedDiff),
        };
    };

    return (
        <section className="w-full py-20 mt-7 overflow-hidden relative border-t border-b border-white/10 rounded-xl before:absolute before:w-30 before:h-30 before:bg-[#c65bd5] before:rounded-full before:top-2 before:left-[40%] before:blur-3xl after:absolute after:w-30 after:h-30 after:bg-[#622ba4] after:rounded-full after:top-2 after:left-[50%] after:blur-3xl" id="projects">
            <div className="container mx-auto px-6">
                
                {/* Header */}
                <motion.div 
                    className="flex flex-col gap-5 justify-center items-center text-center mb-16"
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6 }}
                >
                    <h2 className="text-3xl md:text-5xl font-bold w-[80%] mb-3">
                        Some Slides Generated By AI
                        <span className="text-transparent bg-clip-text bg-linear-to-r from-[#622ba4] to-[#c65bd6]">PPT</span>
                    </h2>
                    <p className="text-lg">
                        See the power of AI in action—smooth, stylish, and ready-to-use slide designs generated in seconds!
                    </p>
                </motion.div>

                {/* 3D Carousel Container */}
                <div className="relative h-[400px] md:h-[500px] mb-16" style={{ perspective: '2000px' }}>
                    <div className="absolute inset-0 flex items-center justify-center" style={{ transformStyle: 'preserve-3d' }}>
                        {slides.map((img, index) => (
                            <motion.div
                                key={index}
                                className="absolute w-[250px] md:w-[400px] h-[180px] md:h-[280px] cursor-pointer"
                                style={{
                                    ...getSlideStyle(index),
                                    transformStyle: 'preserve-3d',
                                    transition: 'all 0.6s cubic-bezier(0.22, 1, 0.36, 1)',
                                }}
                                onClick={() => {
                                    if (index !== currentIndex) {
                                        setCurrentIndex(index);
                                    }
                                }}
                                whileHover={{
                                    scale: index === currentIndex ? 1.05 : 0.95,
                                    transition: { duration: 0.3 }
                                }}
                            >
                                <div className="relative w-full h-full rounded-2xl overflow-hidden shadow-2xl border-2 border-white/10 bg-linear-to-br from-purple-900/20 to-pink-900/20">
                                    <img
                                        src={img}
                                        alt={`slide-${index}`}
                                        className="w-full h-full object-cover"
                                    />
                                    
                                    {/* Overlay for non-center slides */}
                                    {index !== currentIndex && (
                                        <div className="absolute inset-0 bg-black/40 backdrop-blur-[2px]" />
                                    )}
                                    
                                    {/* Glow effect for center slide */}
                                    {index === currentIndex && (
                                        <motion.div
                                            className="absolute inset-0 pointer-events-none"
                                            style={{
                                                boxShadow: '0 0 60px rgba(168, 85, 247, 0.6), 0 0 100px rgba(236, 72, 153, 0.4)',
                                            }}
                                            animate={{
                                                boxShadow: [
                                                    '0 0 60px rgba(168, 85, 247, 0.6), 0 0 100px rgba(236, 72, 153, 0.4)',
                                                    '0 0 80px rgba(168, 85, 247, 0.8), 0 0 120px rgba(236, 72, 153, 0.6)',
                                                    '0 0 60px rgba(168, 85, 247, 0.6), 0 0 100px rgba(236, 72, 153, 0.4)',
                                                ]
                                            }}
                                            transition={{ duration: 2, repeat: Infinity }}
                                        />
                                    )}
                                </div>
                            </motion.div>
                        ))}
                    </div>

                    {/* Navigation Buttons */}
                    <button
                        onClick={handlePrev}
                        className="absolute left-4 top-1/2 -translate-y-1/2 z-20 w-12 h-12 rounded-full bg-white/10 backdrop-blur-md border border-white/20 flex items-center justify-center hover:bg-white/20 transition-all duration-300 group"
                        aria-label="Previous slide"
                    >
                        <FaChevronLeft className="text-white group-hover:-translate-x-1 transition-transform" />
                    </button>
                    
                    <button
                        onClick={handleNext}
                        className="absolute right-4 top-1/2 -translate-y-1/2 z-20 w-12 h-12 rounded-full bg-white/10 backdrop-blur-md border border-white/20 flex items-center justify-center hover:bg-white/20 transition-all duration-300 group"
                        aria-label="Next slide"
                    >
                        <FaChevronRight className="text-white group-hover:translate-x-1 transition-transform" />
                    </button>

                    {/* Dots Indicator */}
                    <div className="absolute bottom-0 left-1/2 -translate-x-1/2 flex gap-2 z-20">
                        {slides.map((_, index) => (
                            <button
                                key={index}
                                onClick={() => setCurrentIndex(index)}
                                className={`w-2 h-2 rounded-full transition-all duration-300 ${
                                    index === currentIndex
                                        ? 'bg-linear-to-r from-purple-500 to-pink-500 w-8'
                                        : 'bg-white/30 hover:bg-white/50'
                                }`}
                                aria-label={`Go to slide ${index + 1}`}
                            />
                        ))}
                    </div>
                </div>

                {/* CTA Button */}
                <motion.div 
                    className="flex justify-center mt-12"
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6, delay: 0.3 }}
                >
                    <motion.button 
                        onClick={() => setIsUser(true)} 
                        className="group btn rounded-lg flex items-center space-x-2 px-6 py-4 duration-100"
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                    >
                        <span>Create Your Own Now</span> 
                        <FaRocket className='group-hover:translate-x-1 group-hover:-translate-y-1 transition' />
                    </motion.button>
                </motion.div>
            </div>
        </section>
    )
}

export default Projects